### ISSUE TITLE
Design: company_jobs-page

### ISSUE THREAD

**Issue by Gato-Gabriel** [LETMIN-Corp/letmin-client#31]
*Obs.:
Todo o texto do site será da fonte "Libre Franklin", a única coisa modificada é o tipo dela (medium, bold, etc...), especificada como "fonte =".

1ª parte

Uma caixa retangular com todas as bordas arredondadas
Na parte esquerda, uma coluna de background color: dark-purple, com redirecionamento de paginas, sendo elas respectivamente "Buscar Vagas" e "Meus Dados", com fonte=medium e cor=gray
Depois da coluna à direita, no canto superior esquerdo o texto "Meus dados" com fonte=medium e cor=black
Abaixo, um espaço para colocar a imagem de perfil e um texto com o nome completo do candidato
Depois em cards:
1. Dados pessoais
2. Descrição sobre si mesmo
3. Formação e experiência prévia
4. Afiliações
5. Atividade no perfil (com um gráfico)
Rodapé

Background color = #7A2AB8
Na direita, o texto "© 2022 - Letmin Corporation", cor #FFFFFF, fonte = medium
Na esquerda, texto "Contato: [letmin.corp@gmail.com](mailto:letmin.corp@gmail.com)", com quebra de linha depois de "Contato:", com cor #FFFFFF, fonte = medium

[Inserção de Vagas.pdf](https://github.com/LETMIN-Corp/letmin-client/files/8940224/Insercao.de.Vagas.pdf)

**Comment by EllenAntonetti** [comment]
**Falta colocar a imagem (em .png) da página**

_Mudei o nome da issue_
