### ISSUE TITLE
Apresentação de vagas criadas

### ISSUE THREAD

**Issue by GabrielNicolim** [LETMIN-Corp/letmin-client#47]
Adicionar vagas criadas à página de indicadores.

![image](https://user-images.githubusercontent.com/69210720/181252866-538620a9-f250-4a6a-bd87-e6e459dad70a.png)

**Comment by EllenAntonetti** [comment]
[vagas.pdf](https://github.com/LETMIN-Corp/letmin-client/files/9219147/vagas.pdf)
![1](https://user-images.githubusercontent.com/82514888/181742112-223837a5-b4da-463f-b1f9-c7382bc7d3ed.png)
![2](https://user-images.githubusercontent.com/82514888/181742121-0453eab3-8ecf-41b5-840b-8bb3cab71cd2.png)

**Comment by GabrielNicolim** [comment]
https://fontawesome.com/search?m=free&s=solid%2Cbrands
