### ISSUE TITLE
Página de apresentação detalhada de vagas 

### ISSUE THREAD

**Issue by GabrielNicolim** [LETMIN-Corp/letmin-client#48]

**Comment by EllenAntonetti** [comment]
[Cópia de vagas.pdf](https://github.com/LETMIN-Corp/letmin-client/files/9219629/Copia.de.vagas.pdf)
![Cópia de vagas](https://user-images.githubusercontent.com/82514888/181752410-646e0a57-7d74-45db-b1cd-7faaec297b17.png)
