### ISSUE TITLE
Perfil do usuário (User)

### ISSUE THREAD

**Issue by GabrielNicolim** [LETMIN-Corp/letmin-client#61]
- [x] Alterar imagem placeholder do perfil do usuário
- [x] Criar um modal para a inserção / edição das informações do perfil do usuário

- [x] Remover borda e adicionar sombra aos cards
- [x] Adicionar botão de ir paga a página de edição na página do usuário
- [x] Adicionar botão de ir para a página do usuário na página de edição
- [x] Fazer consulta de informações do banco funcionar
- [x] Adicionar informações tanto à página de edição quanto a página de usuário
- [x] Fazer edição de nome e descrição funcionar
- [x] Remover "do usuário" do nome do campo
- [x] Fazer inserção de experiência profissional funcionar
- [x] Fazer inserção de experiência formação acadêmica
- [x] Adicionar ícone de lixo à experiência profissional e formação acadêmica
- [x] Possibilitar a exclusão de experiência profissional e formação acadêmica => Utilizar modal de confirmação de exclusão (Atualização perigosa)
- [x] Reduzir ícone de data do modal
- [x] Inverter ordem dos botões de salvar e cancelar
- [x] Jogar os botões de salvar e cancelar para a direita
- [x] Utilizar modal de confirmação de salvamento
- [x] Retornar ao perfil do usuário após a atualização confirmada ou cancelada
- [x] Mostrar username no usuário como parte de uma @

![image](https://user-images.githubusercontent.com/69210720/188496613-5e3a2286-a079-4373-9f4a-6d83ce898af9.png)

**Comment by Gato-Gabriel** [comment]
terminada essa joça
